/* DO NOT EDIT THIS FILE - it is machine generated */
#include <AisinoSSL/sm2jni/jni.h>
/* Header for class com_artifex_cloudcert_CloudCertCore */

#ifndef _Included_com_artifex_cloudcert_CloudCertCore
#define _Included_com_artifex_cloudcert_CloudCertCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_cloudcert_CloudCertCore
 * Method:    sm2MobileKeyGenW
 * Signature: (Lcom/artifex/cloudcert/bean/KeyContext;Lcom/artifex/cloudcert/bean/Point;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_cloudcert_CloudCertCore_sm2MobileKeyGenW
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_artifex_cloudcert_CloudCertCore
 * Method:    sm2MobileKeyGenPa
 * Signature: (Lcom/artifex/cloudcert/bean/KeyContext;Lcom/artifex/cloudcert/bean/Point;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_cloudcert_CloudCertCore_sm2MobileKeyGenPa
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_artifex_cloudcert_CloudCertCore
 * Method:    sm2MobileSignClientFirst
 * Signature: (Lcom/artifex/cloudcert/bean/ClientContext;Lcom/artifex/cloudcert/bean/Point;Lcom/artifex/cloudcert/bean/Point;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_cloudcert_CloudCertCore_sm2MobileSignClientFirst
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_artifex_cloudcert_CloudCertCore
 * Method:    sm2MobileSignClientSecond
 * Signature: (Lcom/artifex/cloudcert/bean/ClientContext;Lcom/artifex/cloudcert/bean/Point;Lcom/artifex/cloudcert/bean/Point;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_cloudcert_CloudCertCore_sm2MobileSignClientSecond
  (JNIEnv *, jclass, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     com_artifex_cloudcert_CloudCertCore
 * Method:    sm2MobileSignClientThird
 * Signature: (Lcom/artifex/cloudcert/bean/ClientContext;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_artifex_cloudcert_CloudCertCore_sm2MobileSignClientThird
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_artifex_cloudcert_CloudCertCore
 * Method:    sm2MobileSignServerFirst
 * Signature: (Lcom/artifex/cloudcert/bean/ServerContext;Lcom/artifex/cloudcert/bean/Point;Lcom/artifex/cloudcert/bean/Point;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_cloudcert_CloudCertCore_sm2MobileSignServerFirst
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_artifex_cloudcert_CloudCertCore
 * Method:    sm2MobileSignServerSecond
 * Signature: (Lcom/artifex/cloudcert/bean/ServerContext;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_cloudcert_CloudCertCore_sm2MobileSignServerSecond
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_artifex_cloudcert_CloudCertCore
 * Method:    sm2MobileSignVerify
 * Signature: (Lcom/artifex/cloudcert/bean/KeyContext;Ljava/lang/String;Ljava/lang/String;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_cloudcert_CloudCertCore_sm2MobileSignVerify
  (JNIEnv *, jclass, jobject, jstring, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
