/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FeistalBox */

#ifndef _Included_FeistalBox
#define _Included_FeistalBox
#ifdef __cplusplus
extern "C" {
#endif
#undef FeistalBox_ENC
#define FeistalBox_ENC 1L
#undef FeistalBox_DEC
#define FeistalBox_DEC 0L
#undef FeistalBox_CBC_MODE
#define FeistalBox_CBC_MODE 1L
#undef FeistalBox_CFB_MODE
#define FeistalBox_CFB_MODE 0L
/*
 * Class:     FeistalBox
 * Method:    getFeistalBoxByte
 * Signature: (Ljava/lang/String;III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_FeistalBox_getFeistalBoxByte
  (JNIEnv *, jclass, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
